version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /Users/aaron/VS_Code/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISABLE_JEMALLOC: true
    restart: unless-stopped
    privileged: true
    network_mode: host
