version: "3"
networks:
  proxy:
    external: true
services:
  server:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=$DB_TYPE
      - FORGEJO__database__HOST=$HOST
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=$USER
      - FORGEJO__database__PASSWD=$PASSWORD
    restart: always
    networks:
      - proxy
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/aaron/docker/postgresql/forgejo:/var/lib/postgresql/data
    ports:
      - 3865:3865
      - 222:22
    labels:
      - traefik.enable=true
      - traefik.http.routers.forgejo.entrypoints=http
      - traefik.http.routers.forgejo.rule=Host(`$URL`)
      - traefik.http.middlewares.forgejo-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.forgejo.middlewares=forgejo-https-redirect
      - traefik.http.routers.forgejo-secure.entrypoints=https
      - traefik.http.routers.forgejo-secure.rule=Host(`$URL`)
      - traefik.http.routers.forgejo-secure.tls=true
      - traefik.http.routers.forgejo-secure.service=forgejo
      - traefik.http.services.forgejo.loadbalancer.server.port=3865
      - traefik.docker.network=proxy
    env_file: .env