version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/aaron/docker/traefik/data/acme.json:/acme.json
    ports:
      - 9050:8080
    environment:
      - TZ=America/Phoenix
      - PUID=1000
      - GUID=568
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`$URL`)"
      - "traefik.http.middlewares.dozzle-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dozzle.middlewares=dozzle-https-redirect"
      - "traefik.http.routers.dozzle-secure.entrypoints=https"
      - "traefik.http.routers.dozzle-secure.rule=Host(`$URL`)"
      - "traefik.http.routers.dozzle-secure.tls=true"
      - "traefik.http.routers.dozzle-secure.service=dozzle"
      - "traefik.http.services.dozzle.loadbalancer.server.port=9050"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle-secure.middlewares=authelia@docker"
    networks:
      - proxy
    restart: unless-stopped
    env_file: .env
networks:
  proxy:
    external: true