version: "3.3"
services:
  fasten:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    container_name: fasten
    volumes:
      - ./db:/opt/fasten/db
      - ./cache:/opt/fasten/cache
      - /home/aaron/docker/traefik/data/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fasten.entrypoints=http"
      - "traefik.http.routers.fasten.rule=Host(`$URL`)"
      - "traefik.http.middlewares.fasten-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.fasten.middlewares=fasten-https-redirect"
      - "traefik.http.routers.fasten-secure.entrypoints=https"
      - "traefik.http.routers.fasten-secure.rule=Host(`$URL`)"
      - "traefik.http.routers.fasten-secure.tls=true"
      - "traefik.http.routers.fasten-secure.service=fasten"
      - "traefik.http.services.fasten.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    networks:
      - proxy
    env_file: .env
networks:
  proxy:
    external: true
    name: proxy