tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    env_file: /home/aaron/docker/tdarr/.env
    environment:
      - TZ=America/Phoenix
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=Nuc11
      - serverIP=$NODE_IP
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - /home/aaron/docker/tdarr/node/configs:/app/configs
      - /home/aaron/docker/tdarr/node/logs:/app/logs
      - /mnt/media:/media
      - /transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]